const Gen = @import("gen.zig");
const StationDefinition = Gen.StationDefinition;

pub fn get() [413]StationDefinition {
    return [_]StationDefinition{
        StationDefinition.init("Abha", .{ .temp_def = .{ .mean = 18.0 } }),
        StationDefinition.init("Abidjan", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Abéché", .{ .temp_def = .{ .mean = 29.4 } }),
        StationDefinition.init("Accra", .{ .temp_def = .{ .mean = 26.4 } }),
        StationDefinition.init("Addis Ababa", .{ .temp_def = .{ .mean = 16.0 } }),
        StationDefinition.init("Adelaide", .{ .temp_def = .{ .mean = 17.3 } }),
        StationDefinition.init("Aden", .{ .temp_def = .{ .mean = 29.1 } }),
        StationDefinition.init("Ahvaz", .{ .temp_def = .{ .mean = 25.4 } }),
        StationDefinition.init("Albuquerque", .{ .temp_def = .{ .mean = 14.0 } }),
        StationDefinition.init("Alexandra", .{ .temp_def = .{ .mean = 11.0 } }),
        StationDefinition.init("Alexandria", .{ .temp_def = .{ .mean = 20.0 } }),
        StationDefinition.init("Algiers", .{ .temp_def = .{ .mean = 18.2 } }),
        StationDefinition.init("Alice Springs", .{ .temp_def = .{ .mean = 21.0 } }),
        StationDefinition.init("Almaty", .{ .temp_def = .{ .mean = 10.0 } }),
        StationDefinition.init("Amsterdam", .{ .temp_def = .{ .mean = 10.2 } }),
        StationDefinition.init("Anadyr", .{ .temp_def = .{ .mean = -6.9 } }),
        StationDefinition.init("Anchorage", .{ .temp_def = .{ .mean = 2.8 } }),
        StationDefinition.init("Andorra la Vella", .{ .temp_def = .{ .mean = 9.8 } }),
        StationDefinition.init("Ankara", .{ .temp_def = .{ .mean = 12.0 } }),
        StationDefinition.init("Antananarivo", .{ .temp_def = .{ .mean = 17.9 } }),
        StationDefinition.init("Antsiranana", .{ .temp_def = .{ .mean = 25.2 } }),
        StationDefinition.init("Arkhangelsk", .{ .temp_def = .{ .mean = 1.3 } }),
        StationDefinition.init("Ashgabat", .{ .temp_def = .{ .mean = 17.1 } }),
        StationDefinition.init("Asmara", .{ .temp_def = .{ .mean = 15.6 } }),
        StationDefinition.init("Assab", .{ .temp_def = .{ .mean = 30.5 } }),
        StationDefinition.init("Astana", .{ .temp_def = .{ .mean = 3.5 } }),
        StationDefinition.init("Athens", .{ .temp_def = .{ .mean = 19.2 } }),
        StationDefinition.init("Atlanta", .{ .temp_def = .{ .mean = 17.0 } }),
        StationDefinition.init("Auckland", .{ .temp_def = .{ .mean = 15.2 } }),
        StationDefinition.init("Austin", .{ .temp_def = .{ .mean = 20.7 } }),
        StationDefinition.init("Baghdad", .{ .temp_def = .{ .mean = 22.77 } }),
        StationDefinition.init("Baguio", .{ .temp_def = .{ .mean = 19.5 } }),
        StationDefinition.init("Baku", .{ .temp_def = .{ .mean = 15.1 } }),
        StationDefinition.init("Baltimore", .{ .temp_def = .{ .mean = 13.1 } }),
        StationDefinition.init("Bamako", .{ .temp_def = .{ .mean = 27.8 } }),
        StationDefinition.init("Bangkok", .{ .temp_def = .{ .mean = 28.6 } }),
        StationDefinition.init("Bangui", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Banjul", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Barcelona", .{ .temp_def = .{ .mean = 18.2 } }),
        StationDefinition.init("Bata", .{ .temp_def = .{ .mean = 25.1 } }),
        StationDefinition.init("Batumi", .{ .temp_def = .{ .mean = 14.0 } }),
        StationDefinition.init("Beijing", .{ .temp_def = .{ .mean = 12.9 } }),
        StationDefinition.init("Beirut", .{ .temp_def = .{ .mean = 20.9 } }),
        StationDefinition.init("Belgrade", .{ .temp_def = .{ .mean = 12.5 } }),
        StationDefinition.init("Belize City", .{ .temp_def = .{ .mean = 26.7 } }),
        StationDefinition.init("Benghazi", .{ .temp_def = .{ .mean = 19.9 } }),
        StationDefinition.init("Bergen", .{ .temp_def = .{ .mean = 7.7 } }),
        StationDefinition.init("Berlin", .{ .temp_def = .{ .mean = 10.3 } }),
        StationDefinition.init("Bilbao", .{ .temp_def = .{ .mean = 14.7 } }),
        StationDefinition.init("Birao", .{ .temp_def = .{ .mean = 26.5 } }),
        StationDefinition.init("Bishkek", .{ .temp_def = .{ .mean = 11.3 } }),
        StationDefinition.init("Bissau", .{ .temp_def = .{ .mean = 27.0 } }),
        StationDefinition.init("Blantyre", .{ .temp_def = .{ .mean = 22.2 } }),
        StationDefinition.init("Bloemfontein", .{ .temp_def = .{ .mean = 15.6 } }),
        StationDefinition.init("Boise", .{ .temp_def = .{ .mean = 11.4 } }),
        StationDefinition.init("Bordeaux", .{ .temp_def = .{ .mean = 14.2 } }),
        StationDefinition.init("Bosaso", .{ .temp_def = .{ .mean = 30.0 } }),
        StationDefinition.init("Boston", .{ .temp_def = .{ .mean = 10.9 } }),
        StationDefinition.init("Bouaké", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Bratislava", .{ .temp_def = .{ .mean = 10.5 } }),
        StationDefinition.init("Brazzaville", .{ .temp_def = .{ .mean = 25.0 } }),
        StationDefinition.init("Bridgetown", .{ .temp_def = .{ .mean = 27.0 } }),
        StationDefinition.init("Brisbane", .{ .temp_def = .{ .mean = 21.4 } }),
        StationDefinition.init("Brussels", .{ .temp_def = .{ .mean = 10.5 } }),
        StationDefinition.init("Bucharest", .{ .temp_def = .{ .mean = 10.8 } }),
        StationDefinition.init("Budapest", .{ .temp_def = .{ .mean = 11.3 } }),
        StationDefinition.init("Bujumbura", .{ .temp_def = .{ .mean = 23.8 } }),
        StationDefinition.init("Bulawayo", .{ .temp_def = .{ .mean = 18.9 } }),
        StationDefinition.init("Burnie", .{ .temp_def = .{ .mean = 13.1 } }),
        StationDefinition.init("Busan", .{ .temp_def = .{ .mean = 15.0 } }),
        StationDefinition.init("Cabo San Lucas", .{ .temp_def = .{ .mean = 23.9 } }),
        StationDefinition.init("Cairns", .{ .temp_def = .{ .mean = 25.0 } }),
        StationDefinition.init("Cairo", .{ .temp_def = .{ .mean = 21.4 } }),
        StationDefinition.init("Calgary", .{ .temp_def = .{ .mean = 4.4 } }),
        StationDefinition.init("Canberra", .{ .temp_def = .{ .mean = 13.1 } }),
        StationDefinition.init("Cape Town", .{ .temp_def = .{ .mean = 16.2 } }),
        StationDefinition.init("Changsha", .{ .temp_def = .{ .mean = 17.4 } }),
        StationDefinition.init("Charlotte", .{ .temp_def = .{ .mean = 16.1 } }),
        StationDefinition.init("Chiang Mai", .{ .temp_def = .{ .mean = 25.8 } }),
        StationDefinition.init("Chicago", .{ .temp_def = .{ .mean = 9.8 } }),
        StationDefinition.init("Chihuahua", .{ .temp_def = .{ .mean = 18.6 } }),
        StationDefinition.init("Chișinău", .{ .temp_def = .{ .mean = 10.2 } }),
        StationDefinition.init("Chittagong", .{ .temp_def = .{ .mean = 25.9 } }),
        StationDefinition.init("Chongqing", .{ .temp_def = .{ .mean = 18.6 } }),
        StationDefinition.init("Christchurch", .{ .temp_def = .{ .mean = 12.2 } }),
        StationDefinition.init("City of San Marino", .{ .temp_def = .{ .mean = 11.8 } }),
        StationDefinition.init("Colombo", .{ .temp_def = .{ .mean = 27.4 } }),
        StationDefinition.init("Columbus", .{ .temp_def = .{ .mean = 11.7 } }),
        StationDefinition.init("Conakry", .{ .temp_def = .{ .mean = 26.4 } }),
        StationDefinition.init("Copenhagen", .{ .temp_def = .{ .mean = 9.1 } }),
        StationDefinition.init("Cotonou", .{ .temp_def = .{ .mean = 27.2 } }),
        StationDefinition.init("Cracow", .{ .temp_def = .{ .mean = 9.3 } }),
        StationDefinition.init("Da Lat", .{ .temp_def = .{ .mean = 17.9 } }),
        StationDefinition.init("Da Nang", .{ .temp_def = .{ .mean = 25.8 } }),
        StationDefinition.init("Dakar", .{ .temp_def = .{ .mean = 24.0 } }),
        StationDefinition.init("Dallas", .{ .temp_def = .{ .mean = 19.0 } }),
        StationDefinition.init("Damascus", .{ .temp_def = .{ .mean = 17.0 } }),
        StationDefinition.init("Dampier", .{ .temp_def = .{ .mean = 26.4 } }),
        StationDefinition.init("Dar es Salaam", .{ .temp_def = .{ .mean = 25.8 } }),
        StationDefinition.init("Darwin", .{ .temp_def = .{ .mean = 27.6 } }),
        StationDefinition.init("Denpasar", .{ .temp_def = .{ .mean = 23.7 } }),
        StationDefinition.init("Denver", .{ .temp_def = .{ .mean = 10.4 } }),
        StationDefinition.init("Detroit", .{ .temp_def = .{ .mean = 10.0 } }),
        StationDefinition.init("Dhaka", .{ .temp_def = .{ .mean = 25.9 } }),
        StationDefinition.init("Dikson", .{ .temp_def = .{ .mean = -11.1 } }),
        StationDefinition.init("Dili", .{ .temp_def = .{ .mean = 26.6 } }),
        StationDefinition.init("Djibouti", .{ .temp_def = .{ .mean = 29.9 } }),
        StationDefinition.init("Dodoma", .{ .temp_def = .{ .mean = 22.7 } }),
        StationDefinition.init("Dolisie", .{ .temp_def = .{ .mean = 24.0 } }),
        StationDefinition.init("Douala", .{ .temp_def = .{ .mean = 26.7 } }),
        StationDefinition.init("Dubai", .{ .temp_def = .{ .mean = 26.9 } }),
        StationDefinition.init("Dublin", .{ .temp_def = .{ .mean = 9.8 } }),
        StationDefinition.init("Dunedin", .{ .temp_def = .{ .mean = 11.1 } }),
        StationDefinition.init("Durban", .{ .temp_def = .{ .mean = 20.6 } }),
        StationDefinition.init("Dushanbe", .{ .temp_def = .{ .mean = 14.7 } }),
        StationDefinition.init("Edinburgh", .{ .temp_def = .{ .mean = 9.3 } }),
        StationDefinition.init("Edmonton", .{ .temp_def = .{ .mean = 4.2 } }),
        StationDefinition.init("El Paso", .{ .temp_def = .{ .mean = 18.1 } }),
        StationDefinition.init("Entebbe", .{ .temp_def = .{ .mean = 21.0 } }),
        StationDefinition.init("Erbil", .{ .temp_def = .{ .mean = 19.5 } }),
        StationDefinition.init("Erzurum", .{ .temp_def = .{ .mean = 5.1 } }),
        StationDefinition.init("Fairbanks", .{ .temp_def = .{ .mean = -2.3 } }),
        StationDefinition.init("Fianarantsoa", .{ .temp_def = .{ .mean = 17.9 } }),
        StationDefinition.init("Flores,  Petén", .{ .temp_def = .{ .mean = 26.4 } }),
        StationDefinition.init("Frankfurt", .{ .temp_def = .{ .mean = 10.6 } }),
        StationDefinition.init("Fresno", .{ .temp_def = .{ .mean = 17.9 } }),
        StationDefinition.init("Fukuoka", .{ .temp_def = .{ .mean = 17.0 } }),
        StationDefinition.init("Gabès", .{ .temp_def = .{ .mean = 19.5 } }),
        StationDefinition.init("Gaborone", .{ .temp_def = .{ .mean = 21.0 } }),
        StationDefinition.init("Gagnoa", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Gangtok", .{ .temp_def = .{ .mean = 15.2 } }),
        StationDefinition.init("Garissa", .{ .temp_def = .{ .mean = 29.3 } }),
        StationDefinition.init("Garoua", .{ .temp_def = .{ .mean = 28.3 } }),
        StationDefinition.init("George Town", .{ .temp_def = .{ .mean = 27.9 } }),
        StationDefinition.init("Ghanzi", .{ .temp_def = .{ .mean = 21.4 } }),
        StationDefinition.init("Gjoa Haven", .{ .temp_def = .{ .mean = -14.4 } }),
        StationDefinition.init("Guadalajara", .{ .temp_def = .{ .mean = 20.9 } }),
        StationDefinition.init("Guangzhou", .{ .temp_def = .{ .mean = 22.4 } }),
        StationDefinition.init("Guatemala City", .{ .temp_def = .{ .mean = 20.4 } }),
        StationDefinition.init("Halifax", .{ .temp_def = .{ .mean = 7.5 } }),
        StationDefinition.init("Hamburg", .{ .temp_def = .{ .mean = 9.7 } }),
        StationDefinition.init("Hamilton", .{ .temp_def = .{ .mean = 13.8 } }),
        StationDefinition.init("Hanga Roa", .{ .temp_def = .{ .mean = 20.5 } }),
        StationDefinition.init("Hanoi", .{ .temp_def = .{ .mean = 23.6 } }),
        StationDefinition.init("Harare", .{ .temp_def = .{ .mean = 18.4 } }),
        StationDefinition.init("Harbin", .{ .temp_def = .{ .mean = 5.0 } }),
        StationDefinition.init("Hargeisa", .{ .temp_def = .{ .mean = 21.7 } }),
        StationDefinition.init("Hat Yai", .{ .temp_def = .{ .mean = 27.0 } }),
        StationDefinition.init("Havana", .{ .temp_def = .{ .mean = 25.2 } }),
        StationDefinition.init("Helsinki", .{ .temp_def = .{ .mean = 5.9 } }),
        StationDefinition.init("Heraklion", .{ .temp_def = .{ .mean = 18.9 } }),
        StationDefinition.init("Hiroshima", .{ .temp_def = .{ .mean = 16.3 } }),
        StationDefinition.init("Ho Chi Minh City", .{ .temp_def = .{ .mean = 27.4 } }),
        StationDefinition.init("Hobart", .{ .temp_def = .{ .mean = 12.7 } }),
        StationDefinition.init("Hong Kong", .{ .temp_def = .{ .mean = 23.3 } }),
        StationDefinition.init("Honiara", .{ .temp_def = .{ .mean = 26.5 } }),
        StationDefinition.init("Honolulu", .{ .temp_def = .{ .mean = 25.4 } }),
        StationDefinition.init("Houston", .{ .temp_def = .{ .mean = 20.8 } }),
        StationDefinition.init("Ifrane", .{ .temp_def = .{ .mean = 11.4 } }),
        StationDefinition.init("Indianapolis", .{ .temp_def = .{ .mean = 11.8 } }),
        StationDefinition.init("Iqaluit", .{ .temp_def = .{ .mean = -9.3 } }),
        StationDefinition.init("Irkutsk", .{ .temp_def = .{ .mean = 1.0 } }),
        StationDefinition.init("Istanbul", .{ .temp_def = .{ .mean = 13.9 } }),
        StationDefinition.init("İzmir", .{ .temp_def = .{ .mean = 17.9 } }),
        StationDefinition.init("Jacksonville", .{ .temp_def = .{ .mean = 20.3 } }),
        StationDefinition.init("Jakarta", .{ .temp_def = .{ .mean = 26.7 } }),
        StationDefinition.init("Jayapura", .{ .temp_def = .{ .mean = 27.0 } }),
        StationDefinition.init("Jerusalem", .{ .temp_def = .{ .mean = 18.3 } }),
        StationDefinition.init("Johannesburg", .{ .temp_def = .{ .mean = 15.5 } }),
        StationDefinition.init("Jos", .{ .temp_def = .{ .mean = 22.8 } }),
        StationDefinition.init("Juba", .{ .temp_def = .{ .mean = 27.8 } }),
        StationDefinition.init("Kabul", .{ .temp_def = .{ .mean = 12.1 } }),
        StationDefinition.init("Kampala", .{ .temp_def = .{ .mean = 20.0 } }),
        StationDefinition.init("Kandi", .{ .temp_def = .{ .mean = 27.7 } }),
        StationDefinition.init("Kankan", .{ .temp_def = .{ .mean = 26.5 } }),
        StationDefinition.init("Kano", .{ .temp_def = .{ .mean = 26.4 } }),
        StationDefinition.init("Kansas City", .{ .temp_def = .{ .mean = 12.5 } }),
        StationDefinition.init("Karachi", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Karonga", .{ .temp_def = .{ .mean = 24.4 } }),
        StationDefinition.init("Kathmandu", .{ .temp_def = .{ .mean = 18.3 } }),
        StationDefinition.init("Khartoum", .{ .temp_def = .{ .mean = 29.9 } }),
        StationDefinition.init("Kingston", .{ .temp_def = .{ .mean = 27.4 } }),
        StationDefinition.init("Kinshasa", .{ .temp_def = .{ .mean = 25.3 } }),
        StationDefinition.init("Kolkata", .{ .temp_def = .{ .mean = 26.7 } }),
        StationDefinition.init("Kuala Lumpur", .{ .temp_def = .{ .mean = 27.3 } }),
        StationDefinition.init("Kumasi", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Kunming", .{ .temp_def = .{ .mean = 15.7 } }),
        StationDefinition.init("Kuopio", .{ .temp_def = .{ .mean = 3.4 } }),
        StationDefinition.init("Kuwait City", .{ .temp_def = .{ .mean = 25.7 } }),
        StationDefinition.init("Kyiv", .{ .temp_def = .{ .mean = 8.4 } }),
        StationDefinition.init("Kyoto", .{ .temp_def = .{ .mean = 15.8 } }),
        StationDefinition.init("La Ceiba", .{ .temp_def = .{ .mean = 26.2 } }),
        StationDefinition.init("La Paz", .{ .temp_def = .{ .mean = 23.7 } }),
        StationDefinition.init("Lagos", .{ .temp_def = .{ .mean = 26.8 } }),
        StationDefinition.init("Lahore", .{ .temp_def = .{ .mean = 24.3 } }),
        StationDefinition.init("Lake Havasu City", .{ .temp_def = .{ .mean = 23.7 } }),
        StationDefinition.init("Lake Tekapo", .{ .temp_def = .{ .mean = 8.7 } }),
        StationDefinition.init("Las Palmas de Gran Canaria", .{ .temp_def = .{ .mean = 21.2 } }),
        StationDefinition.init("Las Vegas", .{ .temp_def = .{ .mean = 20.3 } }),
        StationDefinition.init("Launceston", .{ .temp_def = .{ .mean = 13.1 } }),
        StationDefinition.init("Lhasa", .{ .temp_def = .{ .mean = 7.6 } }),
        StationDefinition.init("Libreville", .{ .temp_def = .{ .mean = 25.9 } }),
        StationDefinition.init("Lisbon", .{ .temp_def = .{ .mean = 17.5 } }),
        StationDefinition.init("Livingstone", .{ .temp_def = .{ .mean = 21.8 } }),
        StationDefinition.init("Ljubljana", .{ .temp_def = .{ .mean = 10.9 } }),
        StationDefinition.init("Lodwar", .{ .temp_def = .{ .mean = 29.3 } }),
        StationDefinition.init("Lomé", .{ .temp_def = .{ .mean = 26.9 } }),
        StationDefinition.init("London", .{ .temp_def = .{ .mean = 11.3 } }),
        StationDefinition.init("Los Angeles", .{ .temp_def = .{ .mean = 18.6 } }),
        StationDefinition.init("Louisville", .{ .temp_def = .{ .mean = 13.9 } }),
        StationDefinition.init("Luanda", .{ .temp_def = .{ .mean = 25.8 } }),
        StationDefinition.init("Lubumbashi", .{ .temp_def = .{ .mean = 20.8 } }),
        StationDefinition.init("Lusaka", .{ .temp_def = .{ .mean = 19.9 } }),
        StationDefinition.init("Luxembourg City", .{ .temp_def = .{ .mean = 9.3 } }),
        StationDefinition.init("Lviv", .{ .temp_def = .{ .mean = 7.8 } }),
        StationDefinition.init("Lyon", .{ .temp_def = .{ .mean = 12.5 } }),
        StationDefinition.init("Madrid", .{ .temp_def = .{ .mean = 15.0 } }),
        StationDefinition.init("Mahajanga", .{ .temp_def = .{ .mean = 26.3 } }),
        StationDefinition.init("Makassar", .{ .temp_def = .{ .mean = 26.7 } }),
        StationDefinition.init("Makurdi", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Malabo", .{ .temp_def = .{ .mean = 26.3 } }),
        StationDefinition.init("Malé", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Managua", .{ .temp_def = .{ .mean = 27.3 } }),
        StationDefinition.init("Manama", .{ .temp_def = .{ .mean = 26.5 } }),
        StationDefinition.init("Mandalay", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Mango", .{ .temp_def = .{ .mean = 28.1 } }),
        StationDefinition.init("Manila", .{ .temp_def = .{ .mean = 28.4 } }),
        StationDefinition.init("Maputo", .{ .temp_def = .{ .mean = 22.8 } }),
        StationDefinition.init("Marrakesh", .{ .temp_def = .{ .mean = 19.6 } }),
        StationDefinition.init("Marseille", .{ .temp_def = .{ .mean = 15.8 } }),
        StationDefinition.init("Maun", .{ .temp_def = .{ .mean = 22.4 } }),
        StationDefinition.init("Medan", .{ .temp_def = .{ .mean = 26.5 } }),
        StationDefinition.init("Mek'ele", .{ .temp_def = .{ .mean = 22.7 } }),
        StationDefinition.init("Melbourne", .{ .temp_def = .{ .mean = 15.1 } }),
        StationDefinition.init("Memphis", .{ .temp_def = .{ .mean = 17.2 } }),
        StationDefinition.init("Mexicali", .{ .temp_def = .{ .mean = 23.1 } }),
        StationDefinition.init("Mexico City", .{ .temp_def = .{ .mean = 17.5 } }),
        StationDefinition.init("Miami", .{ .temp_def = .{ .mean = 24.9 } }),
        StationDefinition.init("Milan", .{ .temp_def = .{ .mean = 13.0 } }),
        StationDefinition.init("Milwaukee", .{ .temp_def = .{ .mean = 8.9 } }),
        StationDefinition.init("Minneapolis", .{ .temp_def = .{ .mean = 7.8 } }),
        StationDefinition.init("Minsk", .{ .temp_def = .{ .mean = 6.7 } }),
        StationDefinition.init("Mogadishu", .{ .temp_def = .{ .mean = 27.1 } }),
        StationDefinition.init("Mombasa", .{ .temp_def = .{ .mean = 26.3 } }),
        StationDefinition.init("Monaco", .{ .temp_def = .{ .mean = 16.4 } }),
        StationDefinition.init("Moncton", .{ .temp_def = .{ .mean = 6.1 } }),
        StationDefinition.init("Monterrey", .{ .temp_def = .{ .mean = 22.3 } }),
        StationDefinition.init("Montreal", .{ .temp_def = .{ .mean = 6.8 } }),
        StationDefinition.init("Moscow", .{ .temp_def = .{ .mean = 5.8 } }),
        StationDefinition.init("Mumbai", .{ .temp_def = .{ .mean = 27.1 } }),
        StationDefinition.init("Murmansk", .{ .temp_def = .{ .mean = 0.6 } }),
        StationDefinition.init("Muscat", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Mzuzu", .{ .temp_def = .{ .mean = 17.7 } }),
        StationDefinition.init("N'Djamena", .{ .temp_def = .{ .mean = 28.3 } }),
        StationDefinition.init("Naha", .{ .temp_def = .{ .mean = 23.1 } }),
        StationDefinition.init("Nairobi", .{ .temp_def = .{ .mean = 17.8 } }),
        StationDefinition.init("Nakhon Ratchasima", .{ .temp_def = .{ .mean = 27.3 } }),
        StationDefinition.init("Napier", .{ .temp_def = .{ .mean = 14.6 } }),
        StationDefinition.init("Napoli", .{ .temp_def = .{ .mean = 15.9 } }),
        StationDefinition.init("Nashville", .{ .temp_def = .{ .mean = 15.4 } }),
        StationDefinition.init("Nassau", .{ .temp_def = .{ .mean = 24.6 } }),
        StationDefinition.init("Ndola", .{ .temp_def = .{ .mean = 20.3 } }),
        StationDefinition.init("New Delhi", .{ .temp_def = .{ .mean = 25.0 } }),
        StationDefinition.init("New Orleans", .{ .temp_def = .{ .mean = 20.7 } }),
        StationDefinition.init("New York City", .{ .temp_def = .{ .mean = 12.9 } }),
        StationDefinition.init("Ngaoundéré", .{ .temp_def = .{ .mean = 22.0 } }),
        StationDefinition.init("Niamey", .{ .temp_def = .{ .mean = 29.3 } }),
        StationDefinition.init("Nicosia", .{ .temp_def = .{ .mean = 19.7 } }),
        StationDefinition.init("Niigata", .{ .temp_def = .{ .mean = 13.9 } }),
        StationDefinition.init("Nouadhibou", .{ .temp_def = .{ .mean = 21.3 } }),
        StationDefinition.init("Nouakchott", .{ .temp_def = .{ .mean = 25.7 } }),
        StationDefinition.init("Novosibirsk", .{ .temp_def = .{ .mean = 1.7 } }),
        StationDefinition.init("Nuuk", .{ .temp_def = .{ .mean = -1.4 } }),
        StationDefinition.init("Odesa", .{ .temp_def = .{ .mean = 10.7 } }),
        StationDefinition.init("Odienné", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Oklahoma City", .{ .temp_def = .{ .mean = 15.9 } }),
        StationDefinition.init("Omaha", .{ .temp_def = .{ .mean = 10.6 } }),
        StationDefinition.init("Oranjestad", .{ .temp_def = .{ .mean = 28.1 } }),
        StationDefinition.init("Oslo", .{ .temp_def = .{ .mean = 5.7 } }),
        StationDefinition.init("Ottawa", .{ .temp_def = .{ .mean = 6.6 } }),
        StationDefinition.init("Ouagadougou", .{ .temp_def = .{ .mean = 28.3 } }),
        StationDefinition.init("Ouahigouya", .{ .temp_def = .{ .mean = 28.6 } }),
        StationDefinition.init("Ouarzazate", .{ .temp_def = .{ .mean = 18.9 } }),
        StationDefinition.init("Oulu", .{ .temp_def = .{ .mean = 2.7 } }),
        StationDefinition.init("Palembang", .{ .temp_def = .{ .mean = 27.3 } }),
        StationDefinition.init("Palermo", .{ .temp_def = .{ .mean = 18.5 } }),
        StationDefinition.init("Palm Springs", .{ .temp_def = .{ .mean = 24.5 } }),
        StationDefinition.init("Palmerston North", .{ .temp_def = .{ .mean = 13.2 } }),
        StationDefinition.init("Panama City", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Parakou", .{ .temp_def = .{ .mean = 26.8 } }),
        StationDefinition.init("Paris", .{ .temp_def = .{ .mean = 12.3 } }),
        StationDefinition.init("Perth", .{ .temp_def = .{ .mean = 18.7 } }),
        StationDefinition.init("Petropavlovsk-Kamchatsky", .{ .temp_def = .{ .mean = 1.9 } }),
        StationDefinition.init("Philadelphia", .{ .temp_def = .{ .mean = 13.2 } }),
        StationDefinition.init("Phnom Penh", .{ .temp_def = .{ .mean = 28.3 } }),
        StationDefinition.init("Phoenix", .{ .temp_def = .{ .mean = 23.9 } }),
        StationDefinition.init("Pittsburgh", .{ .temp_def = .{ .mean = 10.8 } }),
        StationDefinition.init("Podgorica", .{ .temp_def = .{ .mean = 15.3 } }),
        StationDefinition.init("Pointe-Noire", .{ .temp_def = .{ .mean = 26.1 } }),
        StationDefinition.init("Pontianak", .{ .temp_def = .{ .mean = 27.7 } }),
        StationDefinition.init("Port Moresby", .{ .temp_def = .{ .mean = 26.9 } }),
        StationDefinition.init("Port Sudan", .{ .temp_def = .{ .mean = 28.4 } }),
        StationDefinition.init("Port Vila", .{ .temp_def = .{ .mean = 24.3 } }),
        StationDefinition.init("Port-Gentil", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Portland", .{ .temp_def = .{ .mean = 12.4 } }),
        StationDefinition.init("Porto", .{ .temp_def = .{ .mean = 15.7 } }),
        StationDefinition.init("Prague", .{ .temp_def = .{ .mean = 8.4 } }),
        StationDefinition.init("Praia", .{ .temp_def = .{ .mean = 24.4 } }),
        StationDefinition.init("Pretoria", .{ .temp_def = .{ .mean = 18.2 } }),
        StationDefinition.init("Pyongyang", .{ .temp_def = .{ .mean = 10.8 } }),
        StationDefinition.init("Rabat", .{ .temp_def = .{ .mean = 17.2 } }),
        StationDefinition.init("Rangpur", .{ .temp_def = .{ .mean = 24.4 } }),
        StationDefinition.init("Reggane", .{ .temp_def = .{ .mean = 28.3 } }),
        StationDefinition.init("Reykjavík", .{ .temp_def = .{ .mean = 4.3 } }),
        StationDefinition.init("Riga", .{ .temp_def = .{ .mean = 6.2 } }),
        StationDefinition.init("Riyadh", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Rome", .{ .temp_def = .{ .mean = 15.2 } }),
        StationDefinition.init("Roseau", .{ .temp_def = .{ .mean = 26.2 } }),
        StationDefinition.init("Rostov-on-Don", .{ .temp_def = .{ .mean = 9.9 } }),
        StationDefinition.init("Sacramento", .{ .temp_def = .{ .mean = 16.3 } }),
        StationDefinition.init("Saint Petersburg", .{ .temp_def = .{ .mean = 5.8 } }),
        StationDefinition.init("Saint-Pierre", .{ .temp_def = .{ .mean = 5.7 } }),
        StationDefinition.init("Salt Lake City", .{ .temp_def = .{ .mean = 11.6 } }),
        StationDefinition.init("San Antonio", .{ .temp_def = .{ .mean = 20.8 } }),
        StationDefinition.init("San Diego", .{ .temp_def = .{ .mean = 17.8 } }),
        StationDefinition.init("San Francisco", .{ .temp_def = .{ .mean = 14.6 } }),
        StationDefinition.init("San Jose", .{ .temp_def = .{ .mean = 16.4 } }),
        StationDefinition.init("San José", .{ .temp_def = .{ .mean = 22.6 } }),
        StationDefinition.init("San Juan", .{ .temp_def = .{ .mean = 27.2 } }),
        StationDefinition.init("San Salvador", .{ .temp_def = .{ .mean = 23.1 } }),
        StationDefinition.init("Sana'a", .{ .temp_def = .{ .mean = 20.0 } }),
        StationDefinition.init("Santo Domingo", .{ .temp_def = .{ .mean = 25.9 } }),
        StationDefinition.init("Sapporo", .{ .temp_def = .{ .mean = 8.9 } }),
        StationDefinition.init("Sarajevo", .{ .temp_def = .{ .mean = 10.1 } }),
        StationDefinition.init("Saskatoon", .{ .temp_def = .{ .mean = 3.3 } }),
        StationDefinition.init("Seattle", .{ .temp_def = .{ .mean = 11.3 } }),
        StationDefinition.init("Ségou", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Seoul", .{ .temp_def = .{ .mean = 12.5 } }),
        StationDefinition.init("Seville", .{ .temp_def = .{ .mean = 19.2 } }),
        StationDefinition.init("Shanghai", .{ .temp_def = .{ .mean = 16.7 } }),
        StationDefinition.init("Singapore", .{ .temp_def = .{ .mean = 27.0 } }),
        StationDefinition.init("Skopje", .{ .temp_def = .{ .mean = 12.4 } }),
        StationDefinition.init("Sochi", .{ .temp_def = .{ .mean = 14.2 } }),
        StationDefinition.init("Sofia", .{ .temp_def = .{ .mean = 10.6 } }),
        StationDefinition.init("Sokoto", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Split", .{ .temp_def = .{ .mean = 16.1 } }),
        StationDefinition.init("St. John's", .{ .temp_def = .{ .mean = 5.0 } }),
        StationDefinition.init("St. Louis", .{ .temp_def = .{ .mean = 13.9 } }),
        StationDefinition.init("Stockholm", .{ .temp_def = .{ .mean = 6.6 } }),
        StationDefinition.init("Surabaya", .{ .temp_def = .{ .mean = 27.1 } }),
        StationDefinition.init("Suva", .{ .temp_def = .{ .mean = 25.6 } }),
        StationDefinition.init("Suwałki", .{ .temp_def = .{ .mean = 7.2 } }),
        StationDefinition.init("Sydney", .{ .temp_def = .{ .mean = 17.7 } }),
        StationDefinition.init("Tabora", .{ .temp_def = .{ .mean = 23.0 } }),
        StationDefinition.init("Tabriz", .{ .temp_def = .{ .mean = 12.6 } }),
        StationDefinition.init("Taipei", .{ .temp_def = .{ .mean = 23.0 } }),
        StationDefinition.init("Tallinn", .{ .temp_def = .{ .mean = 6.4 } }),
        StationDefinition.init("Tamale", .{ .temp_def = .{ .mean = 27.9 } }),
        StationDefinition.init("Tamanrasset", .{ .temp_def = .{ .mean = 21.7 } }),
        StationDefinition.init("Tampa", .{ .temp_def = .{ .mean = 22.9 } }),
        StationDefinition.init("Tashkent", .{ .temp_def = .{ .mean = 14.8 } }),
        StationDefinition.init("Tauranga", .{ .temp_def = .{ .mean = 14.8 } }),
        StationDefinition.init("Tbilisi", .{ .temp_def = .{ .mean = 12.9 } }),
        StationDefinition.init("Tegucigalpa", .{ .temp_def = .{ .mean = 21.7 } }),
        StationDefinition.init("Tehran", .{ .temp_def = .{ .mean = 17.0 } }),
        StationDefinition.init("Tel Aviv", .{ .temp_def = .{ .mean = 20.0 } }),
        StationDefinition.init("Thessaloniki", .{ .temp_def = .{ .mean = 16.0 } }),
        StationDefinition.init("Thiès", .{ .temp_def = .{ .mean = 24.0 } }),
        StationDefinition.init("Tijuana", .{ .temp_def = .{ .mean = 17.8 } }),
        StationDefinition.init("Timbuktu", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Tirana", .{ .temp_def = .{ .mean = 15.2 } }),
        StationDefinition.init("Toamasina", .{ .temp_def = .{ .mean = 23.4 } }),
        StationDefinition.init("Tokyo", .{ .temp_def = .{ .mean = 15.4 } }),
        StationDefinition.init("Toliara", .{ .temp_def = .{ .mean = 24.1 } }),
        StationDefinition.init("Toluca", .{ .temp_def = .{ .mean = 12.4 } }),
        StationDefinition.init("Toronto", .{ .temp_def = .{ .mean = 9.4 } }),
        StationDefinition.init("Tripoli", .{ .temp_def = .{ .mean = 20.0 } }),
        StationDefinition.init("Tromsø", .{ .temp_def = .{ .mean = 2.9 } }),
        StationDefinition.init("Tucson", .{ .temp_def = .{ .mean = 20.9 } }),
        StationDefinition.init("Tunis", .{ .temp_def = .{ .mean = 18.4 } }),
        StationDefinition.init("Ulaanbaatar", .{ .temp_def = .{ .mean = -0.4 } }),
        StationDefinition.init("Upington", .{ .temp_def = .{ .mean = 20.4 } }),
        StationDefinition.init("Ürümqi", .{ .temp_def = .{ .mean = 7.4 } }),
        StationDefinition.init("Vaduz", .{ .temp_def = .{ .mean = 10.1 } }),
        StationDefinition.init("Valencia", .{ .temp_def = .{ .mean = 18.3 } }),
        StationDefinition.init("Valletta", .{ .temp_def = .{ .mean = 18.8 } }),
        StationDefinition.init("Vancouver", .{ .temp_def = .{ .mean = 10.4 } }),
        StationDefinition.init("Veracruz", .{ .temp_def = .{ .mean = 25.4 } }),
        StationDefinition.init("Vienna", .{ .temp_def = .{ .mean = 10.4 } }),
        StationDefinition.init("Vientiane", .{ .temp_def = .{ .mean = 25.9 } }),
        StationDefinition.init("Villahermosa", .{ .temp_def = .{ .mean = 27.1 } }),
        StationDefinition.init("Vilnius", .{ .temp_def = .{ .mean = 6.0 } }),
        StationDefinition.init("Virginia Beach", .{ .temp_def = .{ .mean = 15.8 } }),
        StationDefinition.init("Vladivostok", .{ .temp_def = .{ .mean = 4.9 } }),
        StationDefinition.init("Warsaw", .{ .temp_def = .{ .mean = 8.5 } }),
        StationDefinition.init("Washington, D.C.", .{ .temp_def = .{ .mean = 14.6 } }),
        StationDefinition.init("Wau", .{ .temp_def = .{ .mean = 27.8 } }),
        StationDefinition.init("Wellington", .{ .temp_def = .{ .mean = 12.9 } }),
        StationDefinition.init("Whitehorse", .{ .temp_def = .{ .mean = -0.1 } }),
        StationDefinition.init("Wichita", .{ .temp_def = .{ .mean = 13.9 } }),
        StationDefinition.init("Willemstad", .{ .temp_def = .{ .mean = 28.0 } }),
        StationDefinition.init("Winnipeg", .{ .temp_def = .{ .mean = 3.0 } }),
        StationDefinition.init("Wrocław", .{ .temp_def = .{ .mean = 9.6 } }),
        StationDefinition.init("Xi'an", .{ .temp_def = .{ .mean = 14.1 } }),
        StationDefinition.init("Yakutsk", .{ .temp_def = .{ .mean = -8.8 } }),
        StationDefinition.init("Yangon", .{ .temp_def = .{ .mean = 27.5 } }),
        StationDefinition.init("Yaoundé", .{ .temp_def = .{ .mean = 23.8 } }),
        StationDefinition.init("Yellowknife", .{ .temp_def = .{ .mean = -4.3 } }),
        StationDefinition.init("Yerevan", .{ .temp_def = .{ .mean = 12.4 } }),
        StationDefinition.init("Yinchuan", .{ .temp_def = .{ .mean = 9.0 } }),
        StationDefinition.init("Zagreb", .{ .temp_def = .{ .mean = 10.7 } }),
        StationDefinition.init("Zanzibar City", .{ .temp_def = .{ .mean = 26.0 } }),
        StationDefinition.init("Zürich", .{ .temp_def = .{ .mean = 9.3 } }),
    };
}
